# Site settings
title: DataViz-KPI
description: Visualization & Analytics
keywords: 
author: itsmecevi
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
